Task3
AnnaKulbicka/voicing-system-anna-kulbicka pull request #3
Opened 2023-03-17 12:51 UTC by AnnaKulbicka

2023-03-18 09:01 UTC, patryk-stepniak requested changes

2023-03-18 09:01 UTC, patryk-stepniak commented on config/checkstyle/checkstyle.xml
> -<?xml version="1.0"?>
Skąd te wszystkie zmiany w tym pliku?

2023-03-18 09:05 UTC, patryk-stepniak requested changes
Masz konflikty z masterem

2023-03-18 09:05 UTC, patryk-stepniak commented on src/test/groovy/pl/futurecollars/invoicing/db/memory/InMemoryDatabaseTest.groovy
> +class InMemoryDatabaseTest extends Specification {
Ten test zawiera zduplikowany kod.
Klasa ta powinna rozszerzać AbstractDatabaseTest.

2023-03-18 09:53 UTC, AnnaKulbicka commented on config/checkstyle/checkstyle.xml
> -<?xml version="1.0"?>
Zmiany w pliku są dlatego że kombinowałam z checkstyle, gdy projekt gradle nie budował się tak jak powinien. Już poprawiłam tak jak powinno być.

2023-03-18 18:03 UTC, patryk-stepniak approved these changes, later dismissed

2023-03-20 18:28 UTC, patryk-stepniak approved these changes

2023-03-20 18:30 UTC, merged